### ISSUE TITLE
Offline example Meteor.status().status issue

### ISSUE THREAD

**Issue by AlmogRnD** [clinical-meteor/software-development-kit#55] opened 2015-01-19 04:58 UTC
With the offline mode example https://github.com/awatson1978/meteor-cookbook/blob/master/cookbook/offline.md 

There is an issue with Meteor.status(), in chrome it always returns connected

**Comment by awatson1978** [comment] 2015-01-19 05:00
How are you testing it?  With airplane mode?

**Comment by almogdesign** [comment] 2015-01-19 05:16
Desktop, turning  my mac wifi off

**Comment by awatson1978** [comment] 2015-01-27 17:12
Sorry for the delay in responding.  Had to go on a roadtrip and visit a client last week.  

Back to the issue...  are you running the client on a phone or tablet?  If you're running the client on the desktop browser, turning wifi off isn't going to affect the connectivity between your desktop browser and Meteor running on your localhost.  They'll still be connected via the loopback network interface.  

Or, if you're testing on a phone/tablet, and your Mac is connected by both WiFi and Ethernet, your phone might be re-routing around the lost WiFi connectivity (as it's designed to do; because networks).

**Comment by realyze** [comment] 2015-10-12 03:30
I'm seeing the same thing: `Meteor.status()` returns `{status: "connected", connected: true, retryCount: 0}` when I'm disconnected (turned wifi off, no ethernet connection).

**Comment by awatson1978** [comment] 2015-10-12 22:38
@realyze - is this on a local machine, or hosted somewhere?  The ethernet loopback will still work, even if there's no ethernet.  But if it's hosted and you're getting that, it might be an actual bug that needs to be reported to MDG with a bug reproduction.

**Comment by awatson1978** [comment] 2016-07-27 01:21
This Meteor Cookbook topic has been migrated to [StackOverflow Documentation](http://stackoverflow.com/documentation/meteor/3375/offline-apps#t=201607270120436457463).  Closing.

**Closed by awatson1978** 2016-07-27 01:21 UTC
